SksCalisma/Areas/Ogrenci/Models/IlanViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SksCalisma.Models;
using SksCalisma.Areas.Ogrenci.Models;

namespace SksCalisma.Areas.Ogrenci.Models
{
    public class IlanViewModel : SksCalisma.Models.Ilan
    {      
        public  bool isChecked { get; set; }
        public  List<String> gunvesaat { get; set; }
        public string bolum { get; set; }
        public string fakulte { get; set; }
    }
}

SksCalisma/Models/Ilan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ilan()
        {
            this.Mulakat = new HashSet<Mulakat>();
            this.OgrenciBasvuru = new HashSet<OgrenciBasvuru>();
        }
    
        public int ilanID { get; set; }
        public int personelID { get; set; }
        public int calismaTipID { get; set; }
        public string ilanMetni { get; set; }
        public System.DateTime ilanEklemeTarih { get; set; }
        public Nullable<System.DateTime> ilanGüncellemeTarih { get; set; }
        public short ilanCalisanSayisi { get; set; }
        public int ogrenimTipID { get; set; }
        public string ilanCalisanGun { get; set; }
    
        public virtual CalismaTip CalismaTip { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual OgrenimTip OgrenimTip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mulakat> Mulakat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciBasvuru> OgrenciBasvuru { get; set; }
    }
}

SksCalisma/Areas/Bolum/Controllers/IlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SksCalisma.Models;

namespace SksCalisma.Areas.Bolum.Controllers
{
    public class IlanController : BaseController
    {
        // GET: Bolum/Ilan
        public ActionResult Index()
        {
            ViewBag.ilanlar = db.Ilan.Where(x => x.personelID == kullaniciID()).ToList();
            return View();
        }

        public ActionResult GetCreateForm()
        {
            ViewBag.calismaTipID = new SelectList(db.CalismaTip, "calismaTipID", "calismaTipAd");
            ViewBag.ogrenimTipID = new SelectList(db.OgrenimTip, "ogrenimTipID", "ogrenimTipAd");
            return PartialView("_Create", new Ilan());
        }
        [HttpPost]
        public ActionResult Create(Ilan ilan)
        {
            ilan.ilanEklemeTarih = DateTime.Now;
            ilan.personelID = kullaniciID();
            db.Ilan.Add(ilan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SksCalisma/Areas/Bolum/Views/Ilan/Index.cshtml
@{
    ViewBag.Title = "Index";
}


@section styles{
    <link href="~/Content/css/bootstrap-select.min.css" rel="stylesheet" />
    <link href="~/Content/css/multi-select.css" rel="stylesheet" />
    <link href="~/Content/css/select2.min.css" rel="stylesheet" />
    <link href="~/Content/css/select2-bootstrap.min.css" rel="stylesheet" />
}
<div class="col-md-6">
    <div class="portlet light">
        <div class="portlet-title">
            <div class="caption font-green">
                <i class="icon-layers font-green"></i>
                <span class="caption-subject bold uppercase">İlanlar</span>
            </div>
            <div class="actions">
                <div class="btn-group">
                    @Ajax.ActionLink("İlan Oluştur", "GetCreateForm", null, new AjaxOptions { OnBegin = "clearArea()", OnComplete = "unblock()", UpdateTargetId = "area", InsertionMode = InsertionMode.Replace }, new { @class = "btn green btn-outline sbold pull-right" })
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="mt-comments">
                @foreach (SksCalisma.Models.Ilan item in ViewBag.ilanlar)
                {
                    <div class="mt-comment">
                        <div class="mt-comment-body">
                            <div class="mt-comment-info">
                                <span class="mt-comment-author">@item.CalismaTip.calismaTipAd - @item.OgrenimTip.ogrenimTipAd - @item.ilanCalisanSayisi</span>
                                <span class="mt-comment-date">@item.OgrenciBasvuru.Count Başvuru</span>
                            </div>
                            <div class="mt-comment-text">@item.ilanMetni</div>
                            <div class="mt-comment-details">
                                <span class="mt-comment-status mt-comment-status-pending"></span>
                                <ul class="mt-comment-actions">
                                    <li>
                                        <a href="#">Düzenle</a>
                                    </li>
                                    <li>
                                        <a href="#">Sil</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="portlet light">
        <div class="portlet-body" id="area">

        </div>
    </div>
</div>
@section scripts{
<script src="~/Content/js/bootstrap-select.min.js"></script>
<script src="~/Content/js/jquery.multi-select.js"></script>
<script src="~/Content/js/select2.full.min.js"></script>
    <script>
        function clearArea()
        {
            $('#area').empty();
            App.blockUI({
                target: '#area',
                boxed: true,
                textOnly: true, 
            });
            $('#area').focus();
        }
        function unblock()
        {
            App.unblockUI('#area');
            $('#my_multi_select2').multiSelect({
                selectableOptgroup: true
            });
            $('.ms-optgroup-label').click(function () {
                var opt = $(this).children('span').html();
                var val = $('#ilanCalisanGun').val();
                var id = $(this).parent().parent().attr('id');
                console.log(id);
                if (id.indexOf('selectable') !== -1) {
                    if (opt == 'Öğleden Önce') {
                        for (var i = 0; i < 5; i++) {
                            val = val.replaceAt(i, '1');
                        }
                    }
                    else if (opt == 'Öğleden Sonra') {
                        for (var i = 5; i < 10; i++) {
                            val = val.replaceAt(i, '1');
                        }
                    }
                }
                else if (id.indexOf('selection') !== -1) {
                    if (opt == 'Öğleden Önce') {
                        for (var i = 0; i < 5; i++) {
                            val = val.replaceAt(i, '0');
                        }
                    }
                    else if (opt == 'Öğleden Sonra') {
                        for (var i = 5; i < 10; i++) {
                            val = val.replaceAt(i, '0');
                        }
                    }
                }
                
                $('#ilanCalisanGun').val(val);
            });
            $('.ms-elem-selectable').click(function () {
                var optGroup = $(this).parent().children().first().children('span').html();
                var opt = $(this).children('span').html();
                var val = $('#ilanCalisanGun').val();
                if (optGroup == 'Öğleden Önce') {
                    switch (opt) {
                        case 'Pazartesi': val = val.replaceAt(0, '1');
                            break;
                        case 'Salı': val = val.replaceAt(1, '1');
                            break;
                        case 'Çarşamba': val = val.replaceAt(2, '1');
                            break;
                        case 'Perşembe': val = val.replaceAt(3, '1');
                            break;
                        case 'Cuma': val = val.replaceAt(4, '1');
                            break;
                    }
                }
                else if (optGroup == 'Öğleden Sonra') {
                    switch (opt) {
                        case 'Pazartesi': val = val.replaceAt(5, '1');
                            break;
                        case 'Salı': val = val.replaceAt(6, '1');
                            break;
                        case 'Çarşamba': val = val.replaceAt(7, '1');
                            break;
                        case 'Perşembe': val = val.replaceAt(8, '1');
                            break;
                        case 'Cuma': val = val.replaceAt(9, '1');
                            break;
                    }
                }
                $('#ilanCalisanGun').val(val);
            })
            $('.ms-elem-selection').click(function () {
                var optGroup = $(this).parent().children().first().children('span').html();
                var opt = $(this).children('span').html();
                var val = $('#ilanCalisanGun').val();
                if (optGroup == 'Öğleden Önce') {
                    switch (opt) {
                        case 'Pazartesi': val = val.replaceAt(0, '0');
                            break;
                        case 'Salı': val = val.replaceAt(1, '0');
                            break;
                        case 'Çarşamba': val = val.replaceAt(2, '0');
                            break;
                        case 'Perşembe': val = val.replaceAt(3, '0');
                            break;
                        case 'Cuma': val = val.replaceAt(4, '0');
                            break;
                    }
                }
                else if (optGroup == 'Öğleden Sonra') {
                    switch (opt) {
                        case 'Pazartesi': val = val.replaceAt(5, '0');
                            break;
                        case 'Salı': val = val.replaceAt(6, '0');
                            break;
                        case 'Çarşamba': val = val.replaceAt(7, '0');
                            break;
                        case 'Perşembe': val = val.replaceAt(8, '0');
                            break;
                        case 'Cuma': val = val.replaceAt(9, '0');
                            break;
                    }
                }
                $('#ilanCalisanGun').val(val);
            })
        }
        String.prototype.replaceAt = function (index, character) {
            return this.substr(0, index) + character + this.substr(index + character.length);
        }
    </script>    
}

SksCalisma/Areas/Bolum/Views/Ilan/_Create.cshtml
@model SksCalisma.Models.Ilan
@using (Html.BeginForm("Create", "Ilan", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.Hidden("ilanCalisanGun", "0000000000")
            <div class="form-group form-md-line-input">
                @Html.LabelFor(model => model.calismaTipID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("calismaTipID", (IEnumerable<SelectListItem>)ViewContext.Controller.ViewBag.calismaTipID, "", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.calismaTipID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group form-md-line-input">
                @Html.LabelFor(model => model.ogrenimTipID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ogrenimTipID", (IEnumerable<SelectListItem>)ViewContext.Controller.ViewBag.ogrenimTipID, "", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ogrenimTipID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group form-md-line-input">
                @Html.LabelFor(model => model.ilanMetni, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ilanMetni, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ilanMetni, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group form-md-line-input">
                @Html.LabelFor(model => model.ilanCalisanSayisi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ilanCalisanSayisi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ilanCalisanSayisi, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group form-md-line-input">
                <label class="control-label col-md-2">Çalışma Günleri</label>
                <div class="col-md-10">
                    <select multiple="multiple" class="multi-select" id="my_multi_select2" name="my_multi_select2[]" style="position: absolute; left: -9999px;">
                        <optgroup label="Öğleden Önce">
                            <option value="1">Pazartesi</option>
                            <option value="2">Salı</option>
                            <option value="3">Çarşamba</option>
                            <option value="4">Perşembe</option>
                            <option value="5">Cuma</option>
                        </optgroup>
                        <optgroup label="Öğleden Sonra">
                            <option value="6">Pazartesi</option>
                            <option value="7">Salı</option>
                            <option value="8">Çarşamba</option>
                            <option value="9">Perşembe</option>
                            <option value="10">Cuma</option>
                        </optgroup>
                    </select>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <div class="row">
                <div class="col-md-offset-10 col-md-2">
                    <button type="submit" class="btn blue">Kaydet</button>
                </div>
            </div>
        </div>
    </div>
}