SksCalisma/Models/AnketSecenek.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketSecenek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnketSecenek()
        {
            this.AnketCevap = new HashSet<AnketCevap>();
        }
    
        public int anketSecenekID { get; set; }
        public int anketSoruID { get; set; }
        public string anketSecenekIcerik { get; set; }
        public short anketSecenekPuan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketCevap> AnketCevap { get; set; }
        public virtual AnketSoru AnketSoru { get; set; }
    }
}

SksCalisma/Areas/Admin/Controllers/AnketSecenekController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SksCalisma.Models;

namespace SksCalisma.Areas.Admin.Controllers
{
    public class AnketSecenekController : BaseController
    {
        // GET: Admin/AnketSecenek
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                ViewBag.soru = false;
                ViewBag.Sorular = new SelectList(db.AnketSoru, "anketSoruID", "anketSoruIcerik");
            }
            else
            {
                ViewBag.soru = true;
                ViewBag.soruID = id;
                ViewBag.Sorular = new SelectList(db.AnketSoru, "anketSoruID", "anketSoruIcerik", id);
                ViewBag.secenekler = db.AnketSecenek.Where(x => x.anketSoruID == id).ToList();
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AnketSecenek secenek)
        {
            if (ModelState.IsValid)
            {
                db.AnketSecenek.Add((secenek));
                db.SaveChanges();
                return RedirectToAction("Index", new { id = secenek.anketSoruID });
            }
            return RedirectToAction("Index", secenek);
        }
        [HttpPost]
        public ActionResult GetEditForm(int id)
        {
            return PartialView("_Edit", db.AnketSecenek.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AnketSecenek secenek)
        {
            if (ModelState.IsValid)
            {
                db.Entry(secenek).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = secenek.anketSoruID });
            }
            return RedirectToAction("Index", new { id = secenek.anketSoruID, secenek });
        }

        [HttpPost]
        public ActionResult GetDeleteForm(int id)
        {
            return PartialView("_Delete", db.AnketSecenek.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var secenek = db.AnketSecenek.Find(id);
            db.AnketSecenek.Remove(secenek);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = secenek.anketSoruID });
        }
    }
}

SksCalisma/Areas/Admin/Views/AnketSecenek/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@section modals{
    <div class="modal fade draggable-modal ui-draggable" id="create" role="basic" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header ui-draggable-handle">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Seçenek Ekle</h4>
                </div>
                @{
                    if ((bool)ViewBag.soru)
                    {
                        @Html.Partial("_Create", new SksCalisma.Models.AnketSecenek() { anketSoruID = ViewBag.soruID })
                    }
                }
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <div class="modal fade draggable-modal ui-draggable" id="editModal" role="basic" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header ui-draggable-handle">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Düzenle</h4>
                </div>
                <div id="editdiv"></div>
                <div id="editloading" class="col-sm-offset-4">
                    <img src="~/Content/img/_LayoutAdmin/loading-spinner-blue.gif" /> Yükleniyor
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <div class="modal fade draggable-modal ui-draggable" id="deleteModal" role="basic" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header ui-draggable-handle">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Sil</h4>
                </div>
                <div id="deletediv"></div>
                <div id="deleteloading" class="col-sm-offset-4">
                    <img src="~/Content/img/_LayoutAdmin/loading-spinner-blue.gif" /> Yükleniyor
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
}
<div class="container">
    <div class="form-group form-md-line-input soruSec">
        @Html.DropDownList("anketSoruID", (IEnumerable<SelectListItem>)ViewContext.Controller.ViewBag.Sorular, "Soru", htmlAttributes: new { @class = "form-control select2 col-sm-8" })
    </div>
</div>
<div class="container" style="margin-top:10px;">
    @{
        if ((bool)ViewBag.soru)
        {
            <div class="box">
                <a class="btn green btn-outline sbold" data-toggle="modal" href="#create"> Seçenek Ekle </a>
            </div><br />
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-cogs"></i>Seçenekler
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                        <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="reload" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="remove" data-original-title="" title=""> </a>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="table-scrollable">
                        <table class="table table-striped table-bordered table-advance table-hover">
                            <thead>
                                <tr>
                                    <th>Secenek</th>
                                    <th>Puan</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ViewBag.secenekler)
                                {
                                    <tr>
                                        <td>
                                            @item.anketSecenekIcerik
                                        </td>
                                        <td>
                                            @item.anketSecenekPuan
                                        </td>
                                        <td>
                                            <button class="btn btn-outline green" type="button" data-toggle="collapse" data-target="@string.Format("#buttonlar{0}", item.anketSecenekID)" aria-expanded="false" aria-controls="@string.Format("buttonlar{0}", item.anketSecenekID)">
                                                <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr class="collapse fade" id="@string.Format("buttonlar{0}", item.anketSecenekID)">
                                        <td colspan="3">
                                            <div class="col-sm-6">
                                                @using (Ajax.BeginForm("GetEditForm", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "editdiv", LoadingElementId = "editloading" }))
                                                {
                                                    <input type="hidden" value="@item.anketSecenekID" name="id" />
                                                    <input type="submit" value="Düzenle" class="btn btn-outline green form-control" data-toggle="modal" data-target="#editModal" />
                                                }
                                            </div>
                                            <div class="col-sm-6">
                                                @using (Ajax.BeginForm("GetDeleteForm", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "deletediv", LoadingElementId = "deleteloading" }))
                                                {
                                                    <input type="hidden" value="@item.anketSecenekID" name="id" />
                                                    <input type="submit" value="Sil" class="btn btn-outline green form-control" data-toggle="modal" data-target="#deleteModal" />
                                                }
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div id="message">
                <h2>Lütfen soru seçin.</h2>
            </div>
        }
    }
    
</div>
@section scripts{
    <script>
        $('.soruSec select').change(function () {
            window.location.pathname = "Admin/AnketSecenek/Index/" + $(this).val();
        })
    </script>
}

SksCalisma/Areas/Admin/Views/AnketSecenek/_Create.cshtml
@model SksCalisma.Models.AnketSecenek

@using (Html.BeginForm("Create", "AnketSecenek", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.anketSoruID)
            <div class="form-group form-md-line-input">
                @Html.LabelFor(model => model.anketSecenekIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.anketSecenekIcerik, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.anketSecenekIcerik, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group form-md-line-input">
                @Html.LabelFor(model => model.anketSecenekPuan, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.anketSecenekPuan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.anketSecenekPuan, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <input type="submit" value="Kaydet" class="btn green" />
    </div>
}

SksCalisma/Areas/Admin/Views/AnketSecenek/_Delete.cshtml
@model SksCalisma.Models.AnketSecenek
@using (Html.BeginForm("Delete", "AnketSecenek", FormMethod.Post, htmlAttributes: new { Area = "Admin" }))
{
    <div class="modal-body">
        @Model.anketSecenekIcerik <br /> Bu anket seçeneğini silmek istediğinize emin misiniz?
    </div>
    <div class="modal-footer">
        @Html.AntiForgeryToken()
        <input type="hidden" value="@Model.anketSecenekID" name="id" />
        <input type="submit" value="Onayla" class="btn green" />
    </div>
}

SksCalisma/Areas/Admin/Views/AnketSecenek/_Edit.cshtml
@model SksCalisma.Models.AnketSecenek

@using (Html.BeginForm("Edit", "AnketSecenek", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.anketSecenekID)
            @Html.HiddenFor(model => model.anketSoruID)

            <div class="form-group form-md-line-input">
                @Html.LabelFor(model => model.anketSecenekIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.anketSecenekIcerik, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.anketSecenekIcerik, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group form-md-line-input">
                @Html.LabelFor(model => model.anketSecenekPuan, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.anketSecenekPuan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.anketSecenekPuan, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <input type="submit" value="Kaydet" class="btn green" />
    </div>
}